---
title: "Untitled"
output: html_document
date: "2023-10-09"
---
```{r}
ytube = read.csv("https://raw.githubusercontent.com/smucciolo/A.nerii_choice_2022/main/ytubesFINAL.csv")
ch_sum <- sum(ytube$CHOSESYR)
ch_inc <- sum(ytube$CHOSEINC)
```


# make all syriaca choices negative
```{r}
negsyr <- ytube
negsyr$CHOSESYR <- negsyr$CHOSESYR*(-1)

#create column for mirror plot
```

```{r}
clean_data <- negsyr
```

```{r}
# adding all values to the new variable
clean_data$choice_sum <- clean_data$CHOSESYR+clean_data$CHOSEINC
 # 0 = no choice 
# for plotting, we cannot use 0 
```

```{r}
library(dplyr)
# get rid of NAs for plot (would report in a manuscript)
```

```{r}
clean_data <- 
  filter(clean_data, clean_data$CHOICE != "NA")
```

```{r}
clean_data[clean_data == "INC"] <- "A.incarnata"
clean_data[clean_data == "SYR"] <- "A.syriaca"

library(ggplot2)
# mirror plot (review why this is needed/ used)
```

## change the x axis 

# final
```{r}
ggplot(clean_data, aes(y=INITIAL, x=choice_sum, fill=CHOICE))+
  geom_col(position="stack")+
  facet_grid(rows=vars(MORPH))+ #we want our panels grouped by aphid morph
  labs(x="Number of Aphids per treatment arm", y="natal host plant")+ #labels
  theme(text=element_text(family = "Avenir", size = 16), legend.position = "top",
        legend.title = element_blank(), 
        axis.title = element_text(size=18),
        plot.title = element_text(size=22), 
        axis.ticks.x=element_blank())+
  scale_fill_manual(values=c("darkolivegreen3", "cyan4"))+
  scale_x_continuous(labels = abs) #absolute values of the axis 
```